version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - amondnet
  ignore:
  - dependency-name: io.netty:netty-codec-http
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.58.Final
    - 4.1.59.Final
    - 4.1.60.Final
    - 4.1.62.Final
